CREATE TABLE AGENTS(
agent_id TEXT PRIMARY KEY UNIQUE NOT NULL,
name TEXT NOT NULL,
gender TEXT NOT NULL,
email TEXT UNIQUE NOT NULL,
assigned_company TEXT NOT NULL,
manager_id TEXT NOT NULL,
password TEXT NOT NULL,
created_on TIMESTAMP NOT NULL,
companies TEXT[]
);

INSERT INTO AGENTS(
AGENT_ID, NAME, GENDER, EMAIL, ASSIGNED_COMPANY,
MANAGER_ID, PASSWORD, CREATED_ON, COMPANIES
) VALUES (
'ONE', 'ANSER', 'MALE', 'anser.shafiq@nastaffing.com', 'NASS','NONE',
'ANY',NOW(),ARRAY['ONE','TWO']
);